name: Test and Merge to Main

on:
  push:
    branches:
      - "feature/*"  # Se activa solo en ramas que empiecen con "feature/"

jobs:
  test-and-merge:
    runs-on: ubuntu-latest

    steps:
      # Configurar GitHub Token y Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Configurar el usuario de Git
      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions [bot]"
          git config user.email "actions@github.com"

      # Ejecutar los tests
      - name: Run Python tests
        run: python -m unittest discover

      # Validar si los tests pasaron
      - name: Check if tests passed
        if: failure()
        run: echo "Tests failed. Aborting merge process." && exit 1

      # Cambiar a la rama feature/*
      - name: Switch to feature branch
        run: git checkout ${{ github.ref_name }}

      # Traer los cambios de main
      - name: Fetch and merge main into feature branch
        run: |
          git fetch origin main
          git merge origin/main --no-ff --no-commit || echo "Merge conflict detected. Aborting merge." && exit 1

      # Hacer el merge de feature/* a main
      - name: Merge feature branch into main
        run: |
          git checkout main
          git merge ${{ github.ref_name }} --no-ff --commit

      # Subir los cambios a main
      - name: Push changes to main
        run: git push origin main
